import type { Org, Profile, SkillGroup, TimelineItem, Work } from './types';

// Shared data for KOKOA portfolio

// --- Data ------------------------------------------------------------
export const PROFILE: Profile = {
  handle: "kokoa0429",
  name: "KOKOA",
  alias: "ciel / ここあ",
  role: "CTO @ WeaverseLab",
  location: "Japan · UTC+09:00",
  tagline_jp: "毎日、ゴミコードを量産してます。",
  tagline_en: "Every day I mass-produce garbage code.",
  bio_jp: "Resonite と VRChat を行ったり来たりしながら、欲しくなった道具はだいたい自分で作ってます。少年アバターが好きで、普段はこんな感じ。ちなみに仕事中はメイド服を着てます。",
  bio_en: "Bouncing between Resonite and VRChat, building whatever tools I end up wanting. I'm into boyish avatars — this is my usual look. FYI, I wear a maid outfit while working.",
  likes: [
    { ico:"♪", label:"Resonite で散歩" },
    { ico:"✶", label:"VRChat でだべる" },
    { ico:"◈", label:"少年アバター" },
    { ico:"❥", label:"仕事中はメイド服" },
    { ico:"◐", label:"夜更かしコーディング" },
    { ico:"✦", label:"ちいさな便利ツール" },
  ],
  links: {
    github: "https://github.com/kokoa0429",
    x: "https://twitter.com/ciel_vr",
    misskey: "https://misskey.resonite.love/@kokoa_",
    resonite: "https://resonite.love/",
  },
};

export const WORKS: Work[] = [
  {
    id: "photo-neos",
    name: "photo.neos.love",
    tag: "Web · Vue",
    year: "2022→",
    role: "Creator / Maintainer",
    summary_jp: "Neos VR / Resonite のスクリーンショット共有サービス。メタデータを保持したまま画像を置いて、ワールド・アバター情報と一緒に公開できる。",
    summary_en: "Screenshot-sharing service for Neos VR / Resonite. Keeps original metadata intact alongside world & avatar context.",
    stack: ["Vue", "TypeScript", "Node.js"],
    stars: 5, forks: 3,
    visibility: "Public",
    accent: "cyan",
  },
  {
    id: "savetowhere",
    name: "SaveToWhere",
    tag: "Desktop · C#",
    year: "2023",
    role: "Author",
    summary_jp: "VRChat や Neos のスクリーンショット保存先を柔軟に振り分けるデスクトップユーティリティ。フォルダ運用地獄からの救出。",
    summary_en: "Desktop utility that routes VRChat / Neos screenshots to folders on rules. Rescue from the Pictures-folder abyss.",
    stack: ["C#", "WPF", "Windows"],
    stars: 12, forks: 0,
    visibility: "Public",
    accent: "lime",
  },
  {
    id: "novelai",
    name: "novelai-metadata-viewer",
    tag: "Web · HTML",
    year: "2023",
    role: "Author",
    summary_jp: "NovelAI で生成された画像の PNG メタデータ（プロンプト・seed 等）を読み出すビューア。ローカルで完結、アップロードなし。",
    summary_en: "Reads PNG metadata (prompts, seeds…) from NovelAI-generated images. Fully local — no upload.",
    stack: ["HTML", "JS", "Canvas"],
    stars: 14, forks: 2,
    visibility: "Public",
    accent: "lime",
  },
  {
    id: "saveexif",
    name: "SaveExif",
    tag: "Desktop · C#",
    year: "archived",
    role: "Author",
    summary_jp: "画像の EXIF 情報を維持しつつ整理するツール。役目を終えて archive 入り。",
    summary_en: "Preserves EXIF while organizing images. Retired and archived.",
    stack: ["C#"],
    stars: 9, forks: 2,
    visibility: "Archived",
    accent: "dim",
  },
  {
    id: "openkokopi",
    name: "OpenKokopi",
    tag: "Experiment · TS",
    year: "2024→",
    role: "Author",
    summary_jp: "個人プロジェクトの実験場。TypeScript で色々試すためのサンドボックス的リポジトリ。",
    summary_en: "Personal sandbox for TypeScript experiments.",
    stack: ["TypeScript"],
    stars: 1, forks: 0,
    visibility: "Public",
    accent: "cyan",
  },
  {
    id: "resonite-love",
    name: "resonite-love",
    tag: "Org · Community",
    year: "2023→",
    role: "Organizer",
    summary_jp: "Resonite 日本語コミュニティ向けの共同プロジェクト群。ツール・ドキュメント・ワールド系を横断。",
    summary_en: "Umbrella org for Japanese Resonite community — tools, docs, world assets.",
    stack: ["Org", "Community"],
    stars: null, forks: null,
    visibility: "Organization",
    accent: "lime",
  },
  {
    id: "concrnt",
    name: "concrnt",
    tag: "Org · Fediverse",
    year: "2024→",
    role: "Contributor",
    summary_jp: "分散型 SNS プロトコル「Concrnt」関連の開発組織に参加。",
    summary_en: "Contributor to Concrnt — a decentralized SNS protocol.",
    stack: ["Org", "Fediverse"],
    stars: null, forks: null,
    visibility: "Organization",
    accent: "cyan",
  },
  {
    id: "weaverse",
    name: "WeaverseLab",
    tag: "Company",
    year: "CTO",
    role: "Chief Technology Officer",
    summary_jp: "本業。VR / Web 横断のプロダクトを手がけるチームの技術責任者として設計と実装をリード。",
    summary_en: "Day job — CTO, leading design & build for a VR / web product team.",
    stack: ["Leadership", "Architecture"],
    stars: null, forks: null,
    visibility: "Company",
    accent: "lime",
  },
];

export const SKILLS: SkillGroup[] = [
  { group: "Frontend", items: ["TypeScript", "Vue", "React", "Next.js", "Vite"] },
  { group: "Backend",  items: ["Node.js", "Express", "PostgreSQL", "Redis", "Docker"] },
  { group: "VR / 3D",  items: ["Resonite", "VRChat SDK", "Unity", "C#", "Blender"] },
  { group: "Infra",    items: ["Linux", "GitHub Actions", "Cloudflare", "nginx", "systemd"] },
];

export const ORGS: Org[] = [
  { name: "WeaverseLab",   role: "CTO",          note: "本業・VR×Web プロダクト" },
  { name: "resonite-love", role: "Organizer",    note: "Resonite JP コミュニティ" },
  { name: "neos-love",     role: "Organizer",    note: "Neos VR JP コミュニティ" },
  { name: "concrnt",       role: "Contributor",  note: "分散型SNSプロトコル" },
  { name: "3dcg-love",     role: "Organizer",    note: "3DCG 学習コミュニティ" },
  { name: "NeosSharedProject", role: "Member",   note: "Neos VR 共有ツール群" },
  { name: "kakuremichi",   role: "Member",       note: "秘密結社系プロジェクト" },
  { name: "uni-pocket",    role: "Member",       note: "Unity 小物置き場" },
  { name: "aa-proj",       role: "Member",       note: "AA プロジェクト" },
  { name: "iaproj",        role: "Member",       note: "旧プロジェクト" },
];

export const TIMELINE: TimelineItem[] = [
  { year: "2024→", title: "WeaverseLab", note: "CTO として創業期の技術全般を担当" },
  { year: "2023→", title: "Resonite 移行", note: "Neos VR の後継として Resonite コミュニティ・ツール開発へ" },
  { year: "2022→", title: "photo.neos.love 公開", note: "ソーシャルVRのスクショ共有サービスを運用開始" },
  { year: "2021→", title: "Neos VR / VRChat 深耕", note: "Unity 拡張と Web ツールを量産し始める" },
];

