import type {
  GalleryPhoto,
  HeroCopyByPersona,
  Org,
  Profile,
  ProfileLinkCard,
  SkillGroup,
  TimelineItem,
  Work,
} from './types';

// Shared data for KOKOA portfolio

// --- Data ------------------------------------------------------------
export const PROFILE: Profile = {
  handle: 'kokoa0429',
  name: 'KOKOA',
  alias: 'ciel / ここあ',
  role: 'CTO @ WeaverseLab',
  location: 'Japan · UTC+09:00',
  tagline_jp: '毎日、ゴミコードを量産してます。',
  tagline_en: 'Every day I mass-produce garbage code.',
  bio_jp:
    'Resonite と VRChat を行ったり来たりしながら、欲しくなった道具はだいたい自分で作ってます。少年アバターが好きで、普段はこんな感じ。ちなみに仕事中はメイド服を着てます。',
  bio_en:
    "Bouncing between Resonite and VRChat, building whatever tools I end up wanting. I'm into boyish avatars — this is my usual look. FYI, I wear a maid outfit while working.",
  likes: [
    { ico: '♪', label: 'Resonite で散歩' },
    { ico: '✶', label: 'VRChat でだべる' },
    { ico: '◈', label: '少年アバター' },
    { ico: '❥', label: '仕事中はメイド服' },
    { ico: '◐', label: '夜更かしコーディング' },
    { ico: '✦', label: 'ちいさな便利ツール' },
  ],
  links: {
    github: 'https://github.com/kokoa0429',
    booth: 'https://kokoa0429.booth.pm/',
    x: 'https://twitter.com/ciel_vr',
    xVrc: 'https://x.com/kka_vrc',
    misskey: 'https://misskey.resonite.love/@kokoa_',
    resonite: 'https://resonite.love/',
  },
};

export const HERO_COPY: HeroCopyByPersona = {
  work: {
    jp: {
      kicker: '仕事の姿',
      body: 'VRやWebをメインに、基板設計やFPGA、IoT周りの開発もしています。フルスタックになりたい。',
      primaryCta: 'Works を見る',
      secondaryCta: 'Links を見る',
      chips: [
        { ico: '01', label: 'VR' },
        { ico: '02', label: 'Web' },
        { ico: '03', label: 'NodeJS' },
        { ico: '04', label: 'FPGA' },
        { ico: '05', label: 'IoT' },
      ],
      floating: ['WeaverseLab', 'いあぷろじぇくと', 'kokoa inc.'],
      panelLines: [
        'const KOKOA = async () => {',
        '  await connect("vr-and-web");',
        '  while (coffee.remaining) {',
        '    ship(await build());',
        '  }',
        '  return betterTools;',
        '};',
        '',
        '// work mode',
        'export default KOKOA;',
      ],
    },
    en: {
      kicker: 'WORK MODE / VR x WEB x HARDWARE',
      body: 'I mainly build around VR and the web, and I also work on PCB design, FPGA, and IoT projects. I want to become a full-stack developer.',
      primaryCta: 'View Works',
      secondaryCta: 'Open Links',
      chips: [
        { ico: '01', label: 'VR' },
        { ico: '02', label: 'Web' },
        { ico: '03', label: 'NodeJS' },
        { ico: '04', label: 'FPGA' },
        { ico: '05', label: 'IoT' },
      ],
      floating: ['WeaverseLab', 'IA Project', 'kokoa inc.'],
      panelLines: [
        'const KOKOA = async () => {',
        '  await connect("vr-and-web");',
        '  while (coffee.remaining) {',
        '    ship(await build());',
        '  }',
        '  return betterTools;',
        '};',
        '',
        '// work mode',
        'export default KOKOA;',
      ],
    },
  },
  hobby: {
    jp: {
      kicker: '作りたいものをつくる！',
      body: 'Resonite と VRChat を行ったり来たりしながら、ワールドを散歩したり、写真を撮ったり、少年アバターでゆっくり過ごしています。 \n 普段過ごす間に作りたくなったものを作って、Boothなどで公開しています！',
      primaryCta: 'Links を見る',
      secondaryCta: 'Works を見る',
      chips: [
        { ico: '♪', label: 'Resoniteで何かを作る' },
        { ico: '✶', label: 'VRChatでだべる' },
        { ico: '◈', label: '少年アバター' },
        { ico: '◉', label: 'Booth' },
        { ico: '◐', label: '創作' },
        { ico: '◇', label: 'ワールド巡り' },
        { ico: '◎', label: '写真を撮る' },
      ],
      floating: ['Resonite', 'VRChat', 'Booth'],
      panelLines: [
        'Resonite world hopping',
        'VRChat friends night',
        'making things in Resonite',
        'Booth release notes',
        'photos after midnight',
        '',
        'status: relaxed',
        'mood: make what I want',
      ],
    },
    en: {
      kicker: 'MAKE WHAT I WANT TO MAKE!',
      body: 'I go back and forth between Resonite and VRChat, wandering worlds, taking photos, and relaxing as a boyish avatar. I make the things I end up wanting during that everyday VR life, then share them on places like Booth.',
      primaryCta: 'Open Links',
      secondaryCta: 'View Works',
      chips: [
        { ico: '♪', label: 'Making things in Resonite' },
        { ico: '✶', label: 'Chatting in VRChat' },
        { ico: '◈', label: 'Boyish avatar' },
        { ico: '◉', label: 'Booth' },
        { ico: '◐', label: 'Making stuff' },
        { ico: '◇', label: 'World hopping' },
        { ico: '◎', label: 'Taking photos' },
      ],
      floating: ['Resonite', 'VRChat', 'Booth'],
      panelLines: [
        'Resonite world hopping',
        'VRChat friends night',
        'making things in Resonite',
        'Booth release notes',
        'photos after midnight',
        '',
        'status: relaxed',
        'mood: make what I want',
      ],
    },
  },
};

export const PROFILE_LINKS: ProfileLinkCard[] = [
  {
    id: 'github',
    href: PROFILE.links.github,
    title: 'GitHub',
    sub: '@kokoa0429',
    icon: 'github',
    note_jp: 'コードと小さな実験を置いています。',
    note_en: 'Code, experiments, and small tools.',
  },
  {
    id: 'x',
    href: PROFILE.links.x,
    title: 'X / Twitter',
    sub: '@ciel_vr',
    icon: 'x',
    note_jp: '日常とVRまわりの軽い更新。',
    note_en: 'Daily notes and VR-adjacent updates.',
  },
  {
    id: 'x-vrc',
    href: PROFILE.links.xVrc,
    title: 'X / VRC',
    sub: '@kka_vrc',
    icon: 'x',
    note_jp: 'VRChat向けの話と更新。',
    note_en: 'VRChat-focused notes and updates.',
  },
  {
    id: 'booth',
    href: PROFILE.links.booth,
    title: 'BOOTH',
    sub: 'kokoa0429.booth.pm',
    icon: 'booth',
    note_jp: '作ったものを置いています。',
    note_en: 'Things I made and publish.',
  },
  {
    id: 'misskey',
    href: PROFILE.links.misskey,
    title: 'Misskey',
    sub: '@kokoa_',
    icon: 'misskey',
    note_jp: 'Resonite寄りの話をゆるく書く場所。',
    note_en: 'Loose notes around Resonite.',
  },
  {
    id: 'resonite',
    href: PROFILE.links.resonite,
    title: 'Resonite',
    sub: 'resonite.love',
    icon: 'resonite',
    note_jp: 'よくいるVRの生活圏。',
    note_en: 'My usual VR home base.',
  },
];

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: 'resonite-closeup',
    src: new URL('../assets/photos/resonite-closeup-2022.jpg', import.meta.url).href,
    caption_jp: 'Resonite / 近すぎる自撮り',
    caption_en: 'Resonite / too-close selfie',
    height: 320,
  },
  {
    id: 'witch-avatar',
    src: new URL('../assets/photos/witch-avatar-2023.jpg', import.meta.url).href,
    caption_jp: '魔女帽子の日',
    caption_en: 'Witch-hat avatar day',
    height: 300,
  },
  {
    id: 'maid-portrait',
    src: new URL('../assets/photos/maid-portrait-2023.jpg', import.meta.url).href,
    caption_jp: 'メイド服ポートレート',
    caption_en: 'Maid outfit portrait',
    height: 360,
  },
  {
    id: 'space-nameplate',
    src: new URL('../assets/photos/space-nameplate-2023.jpg', import.meta.url).href,
    caption_jp: 'kokoa0429 の名札',
    caption_en: 'kokoa0429 nameplate',
    height: 300,
  },
  {
    id: 'maid-sleepy-closeup',
    src: new URL('../assets/photos/maid-sleepy-closeup-2023.jpg', import.meta.url).href,
    caption_jp: '眠そうなメイド',
    caption_en: 'Sleepy maid close-up',
    height: 340,
  },
  {
    id: 'sunset-maid',
    src: new URL('../assets/photos/sunset-maid-2023.jpg', import.meta.url).href,
    caption_jp: '夕焼けの桟橋',
    caption_en: 'Sunset pier',
    height: 320,
  },
  {
    id: 'keylock-clear',
    src: new URL('../assets/photos/keylock-clear-2024.jpg', import.meta.url).href,
    caption_jp: 'KEY LOCK CLEAR',
    caption_en: 'KEY LOCK CLEAR',
    height: 280,
  },
  {
    id: 'maid-room',
    src: new URL('../assets/photos/maid-room-2024.jpg', import.meta.url).href,
    caption_jp: '部屋での一枚',
    caption_en: 'Room portrait',
    height: 320,
  },
  {
    id: 'purple-closeup',
    src: new URL('../assets/photos/purple-closeup-2024.jpg', import.meta.url).href,
    caption_jp: '紫ライトのアップ',
    caption_en: 'Purple-lit close-up',
    height: 340,
  },
  {
    id: 'vrchat-event',
    src: new URL('../assets/photos/vrchat-event-2024.jpg', import.meta.url).href,
    caption_jp: 'イベント会場',
    caption_en: 'VRChat event floor',
    height: 320,
  },
  {
    id: 'neon-stage',
    src: new URL('../assets/photos/neon-stage-2024.jpg', import.meta.url).href,
    caption_jp: 'ネオンステージ',
    caption_en: 'Neon stage',
    height: 320,
  },
  {
    id: 'vrchat-friends',
    src: new URL('../assets/photos/vrchat-friends-2024.jpg', import.meta.url).href,
    caption_jp: 'フレンドと集合',
    caption_en: 'With friends',
    height: 300,
  },
];

export const WORKS: Work[] = [
  {
    id: 'photo-neos',
    name: 'photo.neos.love',
    tag: 'Web · Vue',
    year: '2022→',
    role: 'Creator / Maintainer',
    summary_jp:
      'Neos VR / Resonite のスクリーンショット共有サービス。メタデータを保持したまま画像を置いて、ワールド・アバター情報と一緒に公開できる。',
    summary_en:
      'Screenshot-sharing service for Neos VR / Resonite. Keeps original metadata intact alongside world & avatar context.',
    stack: ['Vue', 'TypeScript', 'Node.js'],
    stars: 5,
    forks: 3,
    visibility: 'Public',
    accent: 'cyan',
  },
  {
    id: 'savetowhere',
    name: 'SaveToWhere',
    tag: 'Desktop · C#',
    year: '2023',
    role: 'Author',
    summary_jp:
      'VRChat や Neos のスクリーンショット保存先を柔軟に振り分けるデスクトップユーティリティ。フォルダ運用地獄からの救出。',
    summary_en:
      'Desktop utility that routes VRChat / Neos screenshots to folders on rules. Rescue from the Pictures-folder abyss.',
    stack: ['C#', 'WPF', 'Windows'],
    stars: 12,
    forks: 0,
    visibility: 'Public',
    accent: 'lime',
  },
  {
    id: 'novelai',
    name: 'novelai-metadata-viewer',
    tag: 'Web · HTML',
    year: '2023',
    role: 'Author',
    summary_jp:
      'NovelAI で生成された画像の PNG メタデータ（プロンプト・seed 等）を読み出すビューア。ローカルで完結、アップロードなし。',
    summary_en: 'Reads PNG metadata (prompts, seeds…) from NovelAI-generated images. Fully local — no upload.',
    stack: ['HTML', 'JS', 'Canvas'],
    stars: 14,
    forks: 2,
    visibility: 'Public',
    accent: 'lime',
  },
  {
    id: 'saveexif',
    name: 'SaveExif',
    tag: 'Desktop · C#',
    year: 'archived',
    role: 'Author',
    summary_jp: '画像の EXIF 情報を維持しつつ整理するツール。役目を終えて archive 入り。',
    summary_en: 'Preserves EXIF while organizing images. Retired and archived.',
    stack: ['C#'],
    stars: 9,
    forks: 2,
    visibility: 'Archived',
    accent: 'dim',
  },
  {
    id: 'openkokopi',
    name: 'OpenKokopi',
    tag: 'Experiment · TS',
    year: '2024→',
    role: 'Author',
    summary_jp: '個人プロジェクトの実験場。TypeScript で色々試すためのサンドボックス的リポジトリ。',
    summary_en: 'Personal sandbox for TypeScript experiments.',
    stack: ['TypeScript'],
    stars: 1,
    forks: 0,
    visibility: 'Public',
    accent: 'cyan',
  },
  {
    id: 'resonite-love',
    name: 'resonite-love',
    tag: 'Org · Community',
    year: '2023→',
    role: 'Organizer',
    summary_jp: 'Resonite 日本語コミュニティ向けの共同プロジェクト群。ツール・ドキュメント・ワールド系を横断。',
    summary_en: 'Umbrella org for Japanese Resonite community — tools, docs, world assets.',
    stack: ['Org', 'Community'],
    stars: null,
    forks: null,
    visibility: 'Organization',
    accent: 'lime',
  },
  {
    id: 'concrnt',
    name: 'concrnt',
    tag: 'Org · Fediverse',
    year: '2024→',
    role: 'Contributor',
    summary_jp: '分散型 SNS プロトコル「Concrnt」関連の開発組織に参加。',
    summary_en: 'Contributor to Concrnt — a decentralized SNS protocol.',
    stack: ['Org', 'Fediverse'],
    stars: null,
    forks: null,
    visibility: 'Organization',
    accent: 'cyan',
  },
  {
    id: 'weaverse',
    name: 'WeaverseLab',
    tag: 'Company',
    year: 'CTO',
    role: 'Chief Technology Officer',
    summary_jp: '本業。VR / Web 横断のプロダクトを手がけるチームの技術責任者として設計と実装をリード。',
    summary_en: 'Day job — CTO, leading design & build for a VR / web product team.',
    stack: ['Leadership', 'Architecture'],
    stars: null,
    forks: null,
    visibility: 'Company',
    accent: 'lime',
  },
];

export const SKILLS: SkillGroup[] = [
  { group: 'Frontend', items: ['TypeScript', 'Vue', 'React', 'Next.js', 'Vite'] },
  { group: 'Backend', items: ['Node.js', 'Express', 'PostgreSQL', 'Redis', 'Docker'] },
  { group: 'VR / 3D', items: ['Resonite', 'VRChat SDK', 'Unity', 'C#', 'Blender'] },
  { group: 'Infra', items: ['Linux', 'GitHub Actions', 'Cloudflare', 'nginx', 'systemd'] },
];

export const ORGS: Org[] = [
  { name: 'WeaverseLab', role: 'CTO', note: '本業・VR×Web プロダクト' },
  { name: 'resonite-love', role: 'Organizer', note: 'Resonite JP コミュニティ' },
  { name: 'neos-love', role: 'Organizer', note: 'Neos VR JP コミュニティ' },
  { name: 'concrnt', role: 'Contributor', note: '分散型SNSプロトコル' },
  { name: '3dcg-love', role: 'Organizer', note: '3DCG 学習コミュニティ' },
  { name: 'NeosSharedProject', role: 'Member', note: 'Neos VR 共有ツール群' },
  { name: 'kakuremichi', role: 'Member', note: '秘密結社系プロジェクト' },
  { name: 'uni-pocket', role: 'Member', note: 'Unity 小物置き場' },
  { name: 'aa-proj', role: 'Member', note: 'AA プロジェクト' },
  { name: 'iaproj', role: 'Member', note: '旧プロジェクト' },
];

export const TIMELINE: TimelineItem[] = [
  { year: '2024→', title: 'WeaverseLab', note: 'CTO として創業期の技術全般を担当' },
  { year: '2023→', title: 'Resonite 移行', note: 'Neos VR の後継として Resonite コミュニティ・ツール開発へ' },
  { year: '2022→', title: 'photo.neos.love 公開', note: 'ソーシャルVRのスクショ共有サービスを運用開始' },
  { year: '2021→', title: 'Neos VR / VRChat 深耕', note: 'Unity 拡張と Web ツールを量産し始める' },
];
